// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9wrCKlzFQ0JdAjTvH2WkDNMnjAB_V6_8',
    appId: '1:971953221659:web:0c669010b63f02cc3d08be',
    messagingSenderId: '971953221659',
    projectId: 'aqua-guard-68df1',
    authDomain: 'aqua-guard-68df1.firebaseapp.com',
    storageBucket: 'aqua-guard-68df1.firebasestorage.app',
    databaseURL: 'https://aqua-guard-68df1-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDduQ8o7vs6nZ7TiZxTfJKhPsYOJMuxw4A',
    appId: '1:971953221659:android:2a4c2c8e3a0f6eec3d08be',
    messagingSenderId: '971953221659',
    projectId: 'aqua-guard-68df1',
    storageBucket: 'aqua-guard-68df1.firebasestorage.app',
    databaseURL: 'https://aqua-guard-68df1-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABO7B8ydNgD8il9UoAE1qIpUJ1QrvveDI',
    appId: '1:971953221659:ios:29be3decd601831f3d08be',
    messagingSenderId: '971953221659',
    projectId: 'aqua-guard-68df1',
    storageBucket: 'aqua-guard-68df1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
    databaseURL: 'https://aqua-guard-68df1-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9wrCKlzFQ0JdAjTvH2WkDNMnjAB_V6_8',
    appId: '1:971953221659:web:71b096576d2dd9ef3d08be',
    messagingSenderId: '971953221659',
    projectId: 'aqua-guard-68df1',
    authDomain: 'aqua-guard-68df1.firebaseapp.com',
    storageBucket: 'aqua-guard-68df1.firebasestorage.app',
    databaseURL: 'https://aqua-guard-68df1-default-rtdb.firebaseio.com',
  );
}
